---
title: "Workout 1"
author: "HAO QIN"
date: "2019/3/13"
output: git_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
curry <- read.csv("stephen-curry.csv",stringsAsFactors=FALSE)
iguodala <- read.csv("andre-iguodala.csv",stringsAsFactors = FALSE)
green <- read.csv("draymond-green.csv",stringsAsFactors = FALSE)
durant <- read.csv("kevin-durant.csv",stringsAsFactors = FALSE)
klay <- read.csv("klay-thompson.csv",stringsAsFactors = FALSE)

ct2 <- 0
cm2 <- 0
ct3 <- 0
cm3 <- 0
for(i in 1:length(curry$shot_type)){
  if(curry$shot_type[i]=="2PT Field Goal" & curry$shot_made_flag[i]=="y"){
    ct2=ct2+1
  cm2=cm2+1}
  else if(curry$shot_type[i]=="2PT Field Goal" & curry$shot_made_flag[i]=="n"){ct2=ct2+1}
    else if(curry$shot_type[i]=="3PT Field Goal" & curry$shot_made_flag[i]=="y"){ct3=ct3+1
    cm3=cm3+1}
  else if(curry$shot_type[i]=="3PT Field Goal" & curry$shot_made_flag[i]=="n"){ct3=ct3+1}
 
}


dt2 <- 0
dm2 <- 0
dt3 <- 0
dm3 <- 0
for(i in 1:length(durant$shot_type)){
if(durant$shot_type[i]=="2PT Field Goal" & durant$shot_made_flag[i]=="y"){
dt2=dt2+1
dm2=dm2+1}
else if(durant$shot_type[i]=="2PT Field Goal" & durant$shot_made_flag[i]=="n"){dt2=dt2+1}
else if(durant$shot_type[i]=="3PT Field Goal" & durant$shot_made_flag[i]=="y"){dt3=dt3+1
dm3=dm3+1}
else if(durant$shot_type[i]=="3PT Field Goal" & durant$shot_made_flag[i]=="n"){dt3=dt3+1}
}

gt2 <- 0
gm2 <- 0
gt3 <- 0
gm3 <- 0
for(i in 1:length(green$shot_type)){
if(green$shot_type[i]=="2PT Field Goal" & green$shot_made_flag[i]=="y"){
gt2=gt2+1
gm2=gm2+1}
else if(green$shot_type[i]=="2PT Field Goal" & green$shot_made_flag[i]=="n"){gt2=gt2+1}
else if(green$shot_type[i]=="3PT Field Goal" & green$shot_made_flag[i]=="y"){gt3=gt3+1
gm3=gm3+1}
else if(green$shot_type[i]=="3PT Field Goal" & green$shot_made_flag[i]=="n"){gt3=gt3+1}
}


it2 <- 0
im2 <- 0
it3 <- 0
im3 <- 0
for(i in 1:length(iguodala$shot_type)){
if(iguodala$shot_type[i]=="2PT Field Goal" & iguodala$shot_made_flag[i]=="y"){
it2=it2+1
im2=im2+1}
else if(iguodala$shot_type[i]=="2PT Field Goal" & iguodala$shot_made_flag[i]=="n"){it2=it2+1}
else if(iguodala$shot_type[i]=="3PT Field Goal" & iguodala$shot_made_flag[i]=="y"){it3=it3+1
im3=im3+1}
else if(iguodala$shot_type[i]=="3PT Field Goal" & iguodala$shot_made_flag[i]=="n"){it3=it3+1}
}

kt2 <- 0
km2 <- 0
kt3 <- 0
km3 <- 0
for(i in 1:length(klay$shot_type)){
if(klay$shot_type[i]=="2PT Field Goal" & klay$shot_made_flag[i]=="y"){
kt2=kt2+1
km2=km2+1}
else if(klay$shot_type[i]=="2PT Field Goal" & klay$shot_made_flag[i]=="n"){kt2=kt2+1}
else if(klay$shot_type[i]=="3PT Field Goal" & klay$shot_made_flag[i]=="y"){kt3=kt3+1
km3=km3+1}
else if(klay$shot_type[i]=="3PT Field Goal" & klay$shot_made_flag[i]=="n"){kt3=kt3+1}
}

PT2 <- data.frame(name=c("curry","durant","green","iguodala","klay"),total=c(ct2,dt2,gt2,it2,kt2),made=c(cm2,dm2,gm2,im2,km2),perc_made=c(cm2/ct2,dm2/dt2,gm2/gt2,im2/it2,km2/kt2))

PT3 <- data.frame(name=c("curry","durant","green","iguodala","klay"),total=c(ct3,dt3,gt3,it3,kt3),made=c(cm3,dm3,gm3,im3,km3),perc_made=c(cm3/ct3,dm3/dt3,gm3/gt3,im3/it3,km3/kt3))

OVR <- data.frame(name=c("curry","durant","green","iguodala","klay"),total=c((ct3+ct2),(dt3+dt2),(gt3+gt2),(it3+it2),(kt3+kt2)),made=c((cm3+cm2),(dm3+dm2),(gm3+gm2),(im3+im2),(km3+km2)),perc_made=c((cm3+cm2)/(ct3+ct2),(dm3+dm2)/(dt3+dt2),(gm3+gm2)/(gt3+gt2),(im3+im2)/(it3+it2),(km3+km2)/(kt3+kt2)))
PT2
PT3
OVR
```